const fs = require('fs');
const path = require('path');

// Default path if not provided
const targetDir = process.argv[2] || 'src/domains/localization/infrastructure/locales';
const localesDir = path.resolve(process.cwd(), targetDir);

console.log(`Setting up languages in: ${localesDir}`);

if (!fs.existsSync(localesDir)) {
    console.error(`❌ Locales directory not found: ${localesDir}`);
    process.exit(1);
}

try {
    // Find all language files (e.g., en-US.ts, tr-TR.ts)
    const files = fs.readdirSync(localesDir)
        .filter(f => f.match(/^[a-z]{2}-[A-Z]{2}\.ts$/))
        .sort();

    const imports = [];
    const exports = [];

    files.forEach(file => {
        const code = file.replace('.ts', '');
        // Remove hyphens for variable names (en-US -> enUS)
        const varName = code.replace(/-([a-z0-9])/g, (g) => g[1].toUpperCase()).replace('-', '');

        imports.push(`import ${varName} from "./${code}";`);
        exports.push(`  "${code}": ${varName},`);
    });

    const content = `/**
 * Localization Index
 * Exports all available translation files
 * Auto-generated by scripts/setup-languages.js
 */

${imports.join('\n')}

export const translations = {
${exports.join('\n')}
};

export type TranslationKey = keyof typeof translations;

export default translations;
`;

    fs.writeFileSync(path.join(localesDir, 'index.ts'), content);
    console.log(`✅ Generated index.ts with ${files.length} languages`);

} catch (error) {
    console.error('❌ Error setting up languages:', error);
    process.exit(1);
}
