#!/usr/bin/env node
/* eslint-disable */
/**
 * Auto-Loader Generator for Localization
 *
 * NOTE: This is a Node.js build script, not React Native code.
 * ESLint is disabled for this file as it uses Node.js APIs (require, __dirname, process, console).
 *
 * Automatically scans locale directories and generates index.ts files
 * that import all .json translation files.
 *
 * Features:
 * - Dynamic JSON file detection (no hardcoded mappings)
 * - Nested namespace structure for better organization
 * - Supports all languages automatically
 * - Clean, maintainable output
 *
 * Usage:
 *   npm run localization:create-loaders        # Generate all
 *   node scripts/createLocaleLoaders.ts en-US  # Generate single language
 *
 * Factory-First: This script is auto-copied to all generated apps
 */

import * as fs from 'fs';
import * as path from 'path';

// Get the locales directory (works from scripts/ or root)
const getLocalesDir = (): string => {
  const possiblePaths: string[] = [
    path.join(__dirname, '../locales'),                    // From scripts/
    path.join(__dirname, 'domains/localization/infrastructure/locales'),  // From root
    path.join(process.cwd(), 'domains/localization/infrastructure/locales'),
  ];

  for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
      return p;
    }
  }

  throw new Error('Could not find locales directory');
};

const localesDir = getLocalesDir();

/**
 * Get all language directories dynamically
 */
function getLanguageDirectories(): string[] {
  return fs
    .readdirSync(localesDir)
    .filter(item => {
      const itemPath = path.join(localesDir, item);
      return fs.statSync(itemPath).isDirectory() && item.match(/^[a-z]{2}-[A-Z]{2}$/);
    })
    .sort();
}

/**
 * Create auto-loader for a single language
 */
function createAutoLoader(languageCode: string): boolean {
  const languageDir = path.join(localesDir, languageCode);

  // Check if directory exists
  if (!fs.existsSync(languageDir)) {
    console.warn(`⚠️  Language directory not found: ${languageCode}`);
    return false;
  }

  // Read all JSON files in the directory
  const files = fs
    .readdirSync(languageDir)
    .filter(file => file.endsWith('.json'))
    .sort();

  if (files.length === 0) {
    console.warn(`⚠️  No JSON files found in: ${languageCode}`);
    return false;
  }

  // Create import statements and namespace mapping
  const imports: string[] = [];
  const namespaces: string[] = [];
  const descriptions: string[] = [];

  files.forEach(file => {
    const moduleName = file.replace('.json', '');
    imports.push(`import ${moduleName} from './${file}';`);
    namespaces.push(moduleName);
    descriptions.push(` * - ${moduleName}: ${file}`);
  });

  // Create the auto-loader content with nested structure
  const content = `/**
 * Auto-generated translation loader for ${languageCode}
 *
 * This file is automatically generated by:
 *   npm run localization:create-loaders
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * Translation Modules:
${descriptions.join('\n')}
 *
 * Generated: ${new Date().toISOString()}
 */

// Import all translation modules
${imports.join('\n')}

// Merge all modules into a single translation object
// Using nested structure for better namespace organization
const translations = {
  ${namespaces.join(',\n  ')},
};

export default translations;
`;

  // Write the index.ts file
  const indexPath = path.join(languageDir, 'index.ts');
  fs.writeFileSync(indexPath, content, 'utf8');

  console.log(`✅ Created auto-loader: ${languageCode}/index.ts (${files.length} modules)`);
  return true;
}

/**
 * Create auto-loaders for all languages
 */
function createAllAutoLoaders(): void {
  const languages = getLanguageDirectories();

  if (languages.length === 0) {
    console.error('❌ No language directories found in:', localesDir);
    process.exit(1);
  }

  console.log(`\n🌍 Creating auto-loaders for ${languages.length} languages...\n`);

  let successCount = 0;
  languages.forEach(languageCode => {
    if (createAutoLoader(languageCode)) {
      successCount++;
    }
  });

  console.log(`\n✨ Successfully created ${successCount}/${languages.length} auto-loaders`);
}

// ============================================================================
// CLI
// ============================================================================

const args = process.argv.slice(2);

if (args[0] === 'all' || args.length === 0) {
  createAllAutoLoaders();
} else if (args[0]) {
  // Single language
  const languageCode = args[0];
  if (createAutoLoader(languageCode)) {
    console.log(`\n✨ Done!`);
  } else {
    console.error(`\n❌ Failed to create auto-loader for: ${languageCode}`);
    process.exit(1);
  }
} else {
  console.log('Usage: node createLocaleLoaders.ts [language-code|all]');
  console.log('\nExamples:');
  console.log('  node createLocaleLoaders.ts           # Generate all');
  console.log('  node createLocaleLoaders.ts all       # Generate all');
  console.log('  node createLocaleLoaders.ts en-US     # Generate single language');
  console.log('  node createLocaleLoaders.ts tr-TR     # Generate single language');
}