/**
 * Auto-loader for en-US translation modules
 *
 * AUTOMATIC TRANSLATION FILE DETECTION:
 * - Uses Metro bundler's require.context to auto-discover .json files
 * - Adding new translation file = just create .json file (zero manual updates)
 * - Build-time resolution (fast, no runtime overhead)
 * - Works for all languages automatically
 *
 * OFFLINE-ONLY TRANSLATIONS (All domains work without backend):
 * - Automatically imports ALL .json files in this directory
 * - Alphabetically sorted for consistency
 * - Type-safe with TypeScript
 *
 * USAGE:
 * 1. Create new translation file: my_domain.json
 * 2. File is auto-discovered and loaded
 * 3. Access via t('my_domain.key')
 *
 * This file is automatically generated by setup-languages.js or createLocaleLoaders.js
 * but can be manually edited if needed.
 *
 * Generated: 2025-11-13T02:01:18.323Z
 */

// Metro bundler require.context - auto-discover all .json files
// eslint-disable-next-line @typescript-eslint/no-require-imports
const translationContext = (require as any).context('./', false, /\.json$/);

/**
 * Load all JSON modules automatically
 * Extracts module name from path (e.g., './auth.json' -> 'auth')
 */
const translations: Record<string, any> = {};

translationContext.keys().forEach((key: string) => {
  // Extract module name from path: './auth.json' -> 'auth'
  const match = key.match(/\.\/([^/]+)\.json$/);
  if (match) {
    const moduleName = match[1];
    translations[moduleName] = translationContext(key);
  }
});

export default translations;
