/**
 * Auto-generated translation loader for vi-VN
 *
 * This file is automatically generated by:
 *   npm run localization:create-loaders
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * Translation Modules:
 * - auth: auth.json
 * - branding: branding.json
 * - datetime: datetime.json
 * - errors: errors.json
 * - flashcards: flashcards.json
 * - general: general.json
 * - navigation: navigation.json
 * - onboarding: onboarding.json
 * - settings: settings.json
 *
 * Generated: 2025-11-06T20:57:31.292Z
 */

// Import all translation modules
// Use require for JSON files to ensure proper Metro bundler handling
const auth = require('./auth.json');
const branding = require('./branding.json');
const datetime = require('./datetime.json');
const errors = require('./errors.json');
const flashcards = require('./flashcards.json');
const general = require('./general.json');
const navigation = require('./navigation.json');
const onboarding = require('./onboarding.json');
const settings = require('./settings.json');

// Merge all modules into a single translation object
// Using nested structure for better namespace organization
const translations = {
  auth,
  branding,
  datetime,
  errors,
  flashcards,
  general,
  navigation,
  onboarding,
  settings,
};

export default translations;
