/**
 * Auto-generated translation loader for en-CA
 *
 * This file is automatically generated by:
 *   npm run localization:create-loaders
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * Translation Modules:
 * - branding: branding.json
 * - datetime: datetime.json
 * - errors: errors.json
 * - flashcards: flashcards.json
 * - general: general.json
 * - navigation: navigation.json
 * - onboarding: onboarding.json
 * - settings: settings.json
 *
 * Generated: 2025-11-06T15:59:47.180Z
 */

// Import all translation modules
import branding from './branding.json';
import datetime from './datetime.json';
import errors from './errors.json';
import flashcards from './flashcards.json';
import general from './general.json';
import navigation from './navigation.json';
import onboarding from './onboarding.json';
import settings from './settings.json';

// Merge all modules into a single translation object
// Using nested structure for better namespace organization
const translations = {
  branding,
  datetime,
  errors,
  flashcards,
  general,
  navigation,
  onboarding,
  settings,
};

export default translations;
